# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teste.ui'
#
# Created: Wed Sep 01 11:19:17 2010
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(762, 529)
        MainWindow.setInputMethodHints(QtCore.Qt.ImhNone)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.editor = Qsci.QsciScintilla(self.centralwidget)
        self.editor.setToolTip("")
        self.editor.setWhatsThis("")
        self.editor.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.editor.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.editor.setObjectName("editor")
        self.verticalLayout.addWidget(self.editor)
        self.plainTextEdit = QtGui.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit.sizePolicy().hasHeightForWidth())
        self.plainTextEdit.setSizePolicy(sizePolicy)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        self.toolBar.setSizeIncrement(QtCore.QSize(0, 0))
        self.toolBar.setBaseSize(QtCore.QSize(0, 0))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.toolBar)
        self.actionNovo = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/imagens/filenew-256.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNovo.setIcon(icon)
        self.actionNovo.setObjectName("actionNovo")
        self.actionAbri = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/imagens/fileopen-256.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbri.setIcon(icon1)
        self.actionAbri.setObjectName("actionAbri")
        self.actionSalvar = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/imagens/filesave-256.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSalvar.setIcon(icon2)
        self.actionSalvar.setObjectName("actionSalvar")
        self.actionCopiar = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/imagens/editcopy-256.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopiar.setIcon(icon3)
        self.actionCopiar.setObjectName("actionCopiar")
        self.actionColar = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/imagens/editpaste-256.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionColar.setIcon(icon4)
        self.actionColar.setObjectName("actionColar")
        self.actionRecortar = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/imagens/editcut-256.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRecortar.setIcon(icon5)
        self.actionRecortar.setObjectName("actionRecortar")
        self.actionCompilar = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/imagens/artsbuilderexecute-256.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCompilar.setIcon(icon6)
        self.actionCompilar.setObjectName("actionCompilar")
        self.actionGerar_Codigo = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/imagens/compfile-256.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGerar_Codigo.setIcon(icon7)
        self.actionGerar_Codigo.setObjectName("actionGerar_Codigo")
        self.actionEquipe = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/imagens/groupevent-256.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEquipe.setIcon(icon8)
        self.actionEquipe.setObjectName("actionEquipe")
        self.toolBar.addAction(self.actionNovo)
        self.toolBar.addAction(self.actionAbri)
        self.toolBar.addAction(self.actionSalvar)
        self.toolBar.addAction(self.actionCopiar)
        self.toolBar.addAction(self.actionColar)
        self.toolBar.addAction(self.actionRecortar)
        self.toolBar.addAction(self.actionCompilar)
        self.toolBar.addAction(self.actionGerar_Codigo)
        self.toolBar.addAction(self.actionEquipe)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Compilador", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNovo.setText(QtGui.QApplication.translate("MainWindow", "Novo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNovo.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbri.setText(QtGui.QApplication.translate("MainWindow", "Abrir", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbri.setToolTip(QtGui.QApplication.translate("MainWindow", "Abrir", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbri.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSalvar.setText(QtGui.QApplication.translate("MainWindow", "Salvar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSalvar.setToolTip(QtGui.QApplication.translate("MainWindow", "Salvar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSalvar.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopiar.setText(QtGui.QApplication.translate("MainWindow", "Copiar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopiar.setToolTip(QtGui.QApplication.translate("MainWindow", "Copiar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopiar.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+C", None, QtGui.QApplication.UnicodeUTF8))
        self.actionColar.setText(QtGui.QApplication.translate("MainWindow", "Colar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionColar.setToolTip(QtGui.QApplication.translate("MainWindow", "Colar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionColar.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+V", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRecortar.setText(QtGui.QApplication.translate("MainWindow", "Recortar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRecortar.setToolTip(QtGui.QApplication.translate("MainWindow", "Recortar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRecortar.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+X", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCompilar.setText(QtGui.QApplication.translate("MainWindow", "Compilar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCompilar.setToolTip(QtGui.QApplication.translate("MainWindow", "Compilar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCompilar.setShortcut(QtGui.QApplication.translate("MainWindow", "F8", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGerar_Codigo.setText(QtGui.QApplication.translate("MainWindow", "Gerar Código", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGerar_Codigo.setToolTip(QtGui.QApplication.translate("MainWindow", "Gerar Código", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGerar_Codigo.setShortcut(QtGui.QApplication.translate("MainWindow", "F9", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEquipe.setText(QtGui.QApplication.translate("MainWindow", "Equipe", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEquipe.setToolTip(QtGui.QApplication.translate("MainWindow", "Equipe", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEquipe.setShortcut(QtGui.QApplication.translate("MainWindow", "F1", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import Qsci
import icons_rc
